/******************************
** File: bx_configuration_api_ddl.sql
** Name: BxConfiguration Managment DDL Script
** Desc: BxConfiguration Managment Tables 
** Auth: Tony Henderson
** Date: 5/22/2020
**************************
** Change History
**************************
** PR   Date        Author  Description 
** --   --------   -------   ------------------------------------
** 1    05/22/2020  Tony   Created
*******************************/

/******************************
** Preparation
*******************************/
DROP TABLE IF EXISTS dbo.BX_ATTRIB_ACCESS_PRIORITY; 
GO  
DROP TABLE IF EXISTS dbo.BX_ATTRIB_TEMPLATE; 
GO  
DROP TABLE IF EXISTS dbo.BX_ATTRIB_VAL_TYPE;  
GO  
DROP TABLE IF EXISTS dbo.BX_CONFIGURATION; 
GO  
DROP TABLE IF EXISTS dbo.BX_CONFIGURATION_ACCESS_PRIORITY;
GO  
DROP TABLE IF EXISTS dbo.BX_CONFIGURATION_ATTRIB_VAL; 
GO  
DROP TABLE IF EXISTS dbo.BX_CONFIGURATION_ATTRIB_VAL_OVERRIDE
GO  
DROP TABLE IF EXISTS dbo.BX_CONFIGURATION_MEDIA; 
GO  
DROP TABLE IF EXISTS dbo.BX_CONFIGURATION_TEMPLATE; 
GO  
DROP TABLE IF EXISTS dbo.BX_CONFIGURATION_TYPE; 
GO  
DROP TABLE IF EXISTS dbo.BX_PRIORITY_RANK; 
GO  

/******************************
** Create
*******************************/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BX_ATTRIB_ACCESS_PRIORITY](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CODE] [varchar](20) NOT NULL,
	[CREATED_BY] [varchar](255) NULL,
	[CREATED_DATE] [datetime2](7) NULL,
	[DESCRIPTION] [varchar](200) NULL,
	[GUID_ID] [varchar](255) NOT NULL,
	[LAST_MODIFIED_BY] [varchar](255) NULL,
	[LAST_MODIFIED_DATE] [datetime2](7) NULL,
	[NAME] [varchar](60) NOT NULL,
	[PRIORITY_RANK_ID] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BX_ATTRIB_ACCESS_PRIORITY] ADD PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BX_ATTRIB_TEMPLATE](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CODE] [varchar](20) NOT NULL,
	[CREATED_BY] [varchar](255) NULL,
	[CREATED_DATE] [datetime2](7) NULL,
	[DESCRIPTION] [varchar](200) NULL,
	[GUID_ID] [varchar](255) NOT NULL,
	[LAST_MODIFIED_BY] [varchar](255) NULL,
	[LAST_MODIFIED_DATE] [datetime2](7) NULL,
	[NAME] [varchar](60) NOT NULL,
	[ATTRIB_VALUE_TYPE_ID] [bigint] NOT NULL,
	[CAN_OVERRIDE] [bit] NOT NULL,
	[CONFIGURATION_MEDIA_ID] [bigint] NULL,
	[CONFIGURATION_TEMPLATE_ID] [bigint] NOT NULL,
	[OPTIONS] [varchar](2000) NULL,
	[VALUE] [varchar](200) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BX_ATTRIB_TEMPLATE] ADD PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BX_ATTRIB_VAL_TYPE](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CODE] [varchar](20) NOT NULL,
	[CREATED_BY] [varchar](255) NULL,
	[CREATED_DATE] [datetime2](7) NULL,
	[DESCRIPTION] [varchar](200) NULL,
	[GUID_ID] [varchar](255) NOT NULL,
	[LAST_MODIFIED_BY] [varchar](255) NULL,
	[LAST_MODIFIED_DATE] [datetime2](7) NULL,
	[NAME] [varchar](60) NOT NULL,
	[CONSTRAINTS] [varchar](2000) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BX_ATTRIB_VAL_TYPE] ADD PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BX_CONFIGURATION](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CREATED_BY] [varchar](255) NULL,
	[CREATED_DATE] [datetime2](7) NULL,
	[DESCRIPTION] [varchar](200) NULL,
	[GUID_ID] [varchar](255) NOT NULL,
	[LAST_MODIFIED_BY] [varchar](255) NULL,
	[LAST_MODIFIED_DATE] [datetime2](7) NULL,
	[NAME] [varchar](40) NULL,
	[CONFIGURATION_GROUP_ID] [bigint] NOT NULL,
	[CONFIGURATION_TEMPLATE_ID] [bigint] NOT NULL,
	[IS_ENABLED] [bit] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BX_CONFIGURATION] ADD PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
SET ANSI_PADDING ON
GO
ALTER TABLE [dbo].[BX_CONFIGURATION] ADD  CONSTRAINT [UK8apy74w50dwpkw18dn7s6xx6y] UNIQUE NONCLUSTERED 
(
	[CONFIGURATION_TEMPLATE_ID] ASC,
	[CONFIGURATION_GROUP_ID] ASC,
	[NAME] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO




SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BX_CONFIGURATION_ACCESS_PRIORITY](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CODE] [varchar](20) NOT NULL,
	[CREATED_BY] [varchar](255) NULL,
	[CREATED_DATE] [datetime2](7) NULL,
	[DESCRIPTION] [varchar](200) NULL,
	[GUID_ID] [varchar](255) NOT NULL,
	[LAST_MODIFIED_BY] [varchar](255) NULL,
	[LAST_MODIFIED_DATE] [datetime2](7) NULL,
	[NAME] [varchar](60) NOT NULL,
	[CONFIGURATION_ID] [bigint] NOT NULL,
	[PRIORITY_RANK_ID] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BX_CONFIGURATION_ACCESS_PRIORITY] ADD PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BX_CONFIGURATION_ACCESS_PRIORITY] ADD  CONSTRAINT [UK_740540sfwhyifsrj2kcb16kx9] UNIQUE NONCLUSTERED 
(
	[CONFIGURATION_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BX_CONFIGURATION_ATTRIB_VAL](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CREATED_BY] [varchar](255) NULL,
	[CREATED_DATE] [datetime2](7) NULL,
	[GUID_ID] [varchar](255) NOT NULL,
	[LAST_MODIFIED_BY] [varchar](255) NULL,
	[LAST_MODIFIED_DATE] [datetime2](7) NULL,
	[SORT_INDEX] [bigint] NOT NULL,
	[ATTRIB_TEMPLATE_ID] [bigint] NOT NULL,
	[CONFIGURATION_ID] [bigint] NOT NULL,
	[CONFIGURATION_MEDIA_ID] [bigint] NULL,
	[OPTIONS] [varchar](255) NULL,
	[VALUE] [varchar](255) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BX_CONFIGURATION_ATTRIB_VAL] ADD PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BX_CONFIGURATION_ATTRIB_VAL] ADD  CONSTRAINT [UKpd2bcxc6kuu65y1aqppovuh03] UNIQUE NONCLUSTERED 
(
	[CONFIGURATION_ID] ASC,
	[ATTRIB_TEMPLATE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO


SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BX_CONFIGURATION_ATTRIB_VAL_OVERRIDE](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CREATED_BY] [varchar](255) NULL,
	[CREATED_DATE] [datetime2](7) NULL,
	[GUID_ID] [varchar](255) NOT NULL,
	[LAST_MODIFIED_BY] [varchar](255) NULL,
	[LAST_MODIFIED_DATE] [datetime2](7) NULL,
	[SORT_INDEX] [bigint] NOT NULL,
	[ATTRIB_ACCESS_PRIORITY_ID] [bigint] NOT NULL,
	[CONFIGURATION_ATTRIB_VAL_ID] [bigint] NOT NULL,
	[OPTIONS] [varchar](2000) NULL,
	[VALUE] [varchar](200) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BX_CONFIGURATION_ATTRIB_VAL_OVERRIDE] ADD PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BX_CONFIGURATION_MEDIA](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CODE] [varchar](20) NOT NULL,
	[CREATED_BY] [varchar](255) NULL,
	[CREATED_DATE] [datetime2](7) NULL,
	[DESCRIPTION] [varchar](200) NULL,
	[GUID_ID] [varchar](255) NOT NULL,
	[LAST_MODIFIED_BY] [varchar](255) NULL,
	[LAST_MODIFIED_DATE] [datetime2](7) NULL,
	[NAME] [varchar](60) NOT NULL,
	[MIME_TYPE] [varchar](30) NULL,
	[URL] [varchar](500) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BX_CONFIGURATION_MEDIA] ADD PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BX_CONFIGURATION_TEMPLATE](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CREATED_BY] [varchar](255) NULL,
	[CREATED_DATE] [datetime2](7) NULL,
	[DESCRIPTION] [varchar](200) NULL,
	[GUID_ID] [varchar](255) NOT NULL,
	[LAST_MODIFIED_BY] [varchar](255) NULL,
	[LAST_MODIFIED_DATE] [datetime2](7) NULL,
	[NAME] [varchar](40) NULL,
	[CONFIGURATION_TYPE_ID] [bigint] NOT NULL,
	[IMAGE_ID] [bigint] NULL,
	[IS_ENABLED] [bit] NOT NULL,
	[THUMB_IMAGE_ID] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BX_CONFIGURATION_TEMPLATE] ADD PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BX_CONFIGURATION_TYPE](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CODE] [varchar](20) NOT NULL,
	[CREATED_BY] [varchar](255) NULL,
	[CREATED_DATE] [datetime2](7) NULL,
	[DESCRIPTION] [varchar](200) NULL,
	[GUID_ID] [varchar](255) NOT NULL,
	[LAST_MODIFIED_BY] [varchar](255) NULL,
	[LAST_MODIFIED_DATE] [datetime2](7) NULL,
	[NAME] [varchar](60) NOT NULL,
	[ICON_ID] [bigint] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BX_CONFIGURATION_TYPE] ADD PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[BX_PRIORITY_RANK](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[CODE] [varchar](20) NOT NULL,
	[CREATED_BY] [varchar](255) NULL,
	[CREATED_DATE] [datetime2](7) NULL,
	[DESCRIPTION] [varchar](200) NULL,
	[GUID_ID] [varchar](255) NOT NULL,
	[LAST_MODIFIED_BY] [varchar](255) NULL,
	[LAST_MODIFIED_DATE] [datetime2](7) NULL,
	[NAME] [varchar](60) NOT NULL,
	[PRIORITY_RANK] [bigint] NOT NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[BX_PRIORITY_RANK] ADD PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

